import { SoalMeresponKaedah } from "@/lib/types";

const soalMerepson:SoalMeresponKaedah[] = [
  {
    "id": 31,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Keputusan rapat itu dianggap sangat **subjektif** oleh beberapa anggota.",
    "kata_x": "subjektif",
    "opsi_x": ["parsial", "berimbang"],
    "dialog_y": "Y: Ya, karena cenderung tidak didasarkan pada data yang **objektif**.",
    "kata_y": "objektif",
    "opsi_y": ["empiris", "emosional"],
    "jawaban_benar": "A",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'subjektif' (bermakna berdasarkan pandangan pribadi) adalah 'parsial' (A), yang berarti memihak atau tidak adil."
  },
  {
    "id": 32,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Penulis novel itu terkenal karena gayanya yang **eksentrik**.",
    "kata_x": "eksentrik",
    "opsi_x": ["aneh", "lumrah"],
    "dialog_y": "Y: Itu membuat karyanya sulit untuk ditiru oleh penulis **konvensional**.",
    "kata_y": "konvensional",
    "opsi_y": ["umum", "unik"],
    "jawaban_benar": "A",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'eksentrik' (bermakna menyimpang dari yang biasa, aneh) adalah 'aneh' (A)."
  },
  {
    "id": 33,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Kehadiran saksi baru itu benar-benar **kontradiktif** dengan pernyataan sebelumnya.",
    "kata_x": "kontradiktif",
    "opsi_x": ["bertentangan", "selaras"],
    "dialog_y": "Y: Ini akan semakin **memperkeruh** jalannya persidangan.",
    "kata_y": "memperkeruh",
    "opsi_y": ["memperjelas", "mengacaukan"],
    "jawaban_benar": "B",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'kontradiktif' adalah 'bertentangan' (A)."
  },
  {
    "id": 34,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Perlu ada **modifikasi** serius pada peraturan lama ini.",
    "kata_x": "modifikasi",
    "opsi_x": ["perubahan", "pembekuan"],
    "dialog_y": "Y: Saya rasa aturannya sudah terlalu **usang** untuk diterapkan sekarang.",
    "kata_y": "usang",
    "opsi_y": ["modern", "kadaluarsa"],
    "jawaban_benar": "A",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'modifikasi' adalah 'perubahan' (A)."
  },
  {
    "id": 35,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Tim peneliti itu akhirnya berhasil menemukan metode yang **efisien**.",
    "kata_x": "efisien",
    "opsi_x": ["boros", "berdaya-guna"],
    "dialog_y": "Y: Artinya, mereka berhasil meminimalkan **pemborosan** sumber daya.",
    "kata_y": "pemborosan",
    "opsi_y": ["penghematan", "kesia-siaan"],
    "jawaban_benar": "B",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'efisien' (bermakna mampu menjalankan tugas dengan tepat dan hemat) adalah 'berdaya-guna' (B)."
  },
  {
    "id": 36,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Perekonomian global mengalami masa **turbulensi** yang cukup lama.",
    "kata_x": "turbulensi",
    "opsi_x": ["gejolak", "keseimbangan"],
    "dialog_y": "Y: Itu membuat pasar menjadi **volatil** dan sulit diprediksi.",
    "kata_y": "volatil",
    "opsi_y": ["stabil", "bergejolak"],
    "jawaban_benar": "A",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'turbulensi' (bermakna kekacauan atau gejolak) adalah 'gejolak' (A)."
  },
  {
    "id": 37,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Anggota dewan telah memberikan **mandat** penuh kepada ketua baru.",
    "kata_x": "mandat",
    "opsi_x": ["perintah", "larangan"],
    "dialog_y": "Y: Itu menunjukkan bahwa mereka memiliki **konfidensi** yang tinggi terhadapnya.",
    "kata_y": "konfidensi",
    "opsi_y": ["ketidakpercayaan", "kepercayaan"],
    "jawaban_benar": "A",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'mandat' (bermakna perintah atau wewenang) adalah 'perintah' (A)."
  },
  {
    "id": 38,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Kita perlu bersikap lebih **pragmatis** dalam menghadapi masalah ini.",
    "kata_x": "pragmatis",
    "opsi_x": ["idealis", "praktis"],
    "dialog_y": "Y: Ya, hindari solusi yang terlalu **teoretis** dan tidak realistis.",
    "kata_y": "teoretis",
    "opsi_y": ["abstrak", "konkret"],
    "jawaban_benar": "B",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'pragmatis' (bermakna berdasarkan fakta dan tindakan praktis) adalah 'praktis' (B)."
  },
  {
    "id": 39,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Laporan itu mengungkapkan adanya **kolusi** dalam tender proyek tersebut.",
    "kata_x": "kolusi",
    "opsi_x": ["persekongkolan", "keterbukaan"],
    "dialog_y": "Y: Artinya, terjadi **penyimpangan** yang merugikan negara.",
    "kata_y": "penyimpangan",
    "opsi_y": ["kepatuhan", "deviasi"],
    "jawaban_benar": "A",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'kolusi' (bermakna persekongkolan rahasia) adalah 'persekongkolan' (A)."
  },
  {
    "id": 40,
    "seksi": "seksi-dua-meresponkaedah",
    "tingkat_kesulitan": "sulit",
    "dialog_x": "X: Kami mencoba membuat sistem yang benar-benar **inheren** dengan budaya perusahaan.",
    "kata_x": "inheren",
    "opsi_x": ["eksternal", "melekat"],
    "dialog_y": "Y: Itu akan membuat sistem menjadi lebih **otonom** dan mandiri.",
    "kata_y": "otonom",
    "opsi_y": ["mandiri", "tergantung"],
    "jawaban_benar": "B",
    "pembahasan": "Padanan kata (sinonim) yang paling tepat untuk 'inheren' (bermakna melekat, tersemat) adalah 'melekat' (B)."
  }
]